### ISSUE TITLE
Migration to version 14.0

### ISSUE THREAD

**Issue by rousseldenis** [OCA/sale-promotion#57]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

# Modules to migrate

- [x] sale_coupon_auto_refresh
- [x] sale_coupon_criteria_multi_product - By @alvaro-domatix - #68
- [x] sale_coupon_multi_gift - By @carolina-domatix - #65
- [x] sale_coupon_order_line_link - By @ilyasProgrammer - #53
- [x] sale_coupon_partner - By @dessanhemrayev - #125

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
