### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/sale-promotion#80]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
- [x] coupon_chatter - By @stefan-tecnativa - #142
- [x] coupon_criteria_multi_product - By @pilarvargas-tecnativa - #184
- [ ] coupon_incompatibility - By @ernesto-garcia-tecnativa - #157
- [x] coupon_limit - By @pilarvargas-tecnativa - #155
- [x] coupon_mass_mailing - By @pilarvargas-tecnativa - #176
- [x] coupon_multi_gift - By @pilarvargas-tecnativa - #181
- [x] sale_coupon_criteria_multi_product - By @pilarvargas-tecnativa - #185
- [x] sale_coupon_incompatibility - By @pilarvargas-tecnativa - #180
- [x] sale_coupon_limit - By @pilarvargas-tecnativa - #156
- [x] sale_coupon_multi_gift - By @pilarvargas-tecnativa - #196
- [x] sale_coupon_order_line_link - By @pilarvargas-tecnativa - #152
- [x] sale_coupon_partner - By @pilarvargas-tecnativa - #154
- [x] sale_loyalty_auto_refresh - By @nguyenminhchien - #208
- [x] website_sale_coupon_page - By @pilarvargas-tecnativa - #149
- [x] website_sale_coupon_selection_wizard - By @pilarvargas-tecnativa - #203
